name: APK AzurLane JMBQ Build Work
on:
  workflow_dispatch:
    inputs:
      server_name:
        description: '服务器名称（如Bilibili）'
        required: true
        type: string
        default: 'Bilibili'
      download_url:
        description: 'APK下载直链'
        required: true
        type: string
        default: 'https://tmp-hd106.vx-cdn.com/file-69ffe33988db9-69ffeb88668be/blhx_9.7.10_0407_20260422_115059_a875e%20%281%29.apk'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: "18"
          distribution: "adopt"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install build-tools
        run: |
          yes | sdkmanager --install "build-tools;35.0.0"
      
      - name: Build APK
        run: |
          chmod +x merge_build.sh
          ./merge_build.sh "${{ github.event.inputs.server_name }}" "${{ github.event.inputs.download_url }}"

      # 先只保留上传Artifacts的步骤，Release步骤暂时去掉，避免格式错误
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AzurLane-${{ github.event.inputs.server_name }}-APK
          path: |
            *.apk
          retention-days: 90
